import type { Metadata } from "next";
//import "..public/sass/style.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Children, Suspense } from "react";
import Header from "./Header"; 
import "./css/googleFonts.css"; 
import { Inter } from "next/font/google";
import "./css/globals.css";
import "./css/bootstrap.min.css"; 
import "./css/lightbox.min.css";  
import "./css/owlcarousel.min.css";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Developersinos" }],
  keywords: [""],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <Suspense>
          <Header />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
